#!/bin/bash

echo -n "CPU temp in deg C         " `cat /sys/devices/virtual/thermal/thermal_zone0/temp` ; echo
echo -n "CPU scaling curr freq Hz  " `cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq` ; echo
echo -n "CPU cpuinfo curr freq Hz  " `cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_cur_freq` ; echo
echo -n "CPU current freq governor " `cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor` ; echo
